markdown: kramdown
permalink: pretty
pygments: true

timezone: UTC

kramdown:
  auto_ids: false

exclude:
  - config
  - config.ru
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - README.md
  - redirect.conf_
  - vendor

url: http://eltrans.github.io

locales:
  sitelinks:
    en:
      - text: About us
        url: /en/about/
      - text: Certificates
        url: /en/certificates/
      - text: Contacts
        url: /en/contact/
      - text: Customers
        url: /en/customers/
      - text: News
        url: /en/news/
      - text: Services
        url: /en/services/
      - text: Maintenance
        url: /en/maintenance/
      - text: Leaders
        url: /en/stuff/
    ru:
      - text: О нас
        url: /ru/about/
      - text: Сертификаты
        url: /ru/certificates/
      - text: Контакты
        url: /ru/contact/
      - text: Клиенты
        url: /ru/customers/
      - text: Новости
        url: /ru/news/
      - text: Услуги
        url: /ru/services/
      - text: Обслуживание
        url: /ru/maintenance/
      - text: Руководство
        url: /ru/stuff/
  news:
    en:
      other_news: Other News
      more_news: More News...
      continue: Continue Reading...
      back_to_year: "Back to %Y Archives"
      recent_news: Recent News
      yearly_archive_title: "%Y Archives"
      monthly_archive_title: "%B %Y Archives"
      yearly_archives: Archives by Year
      monthly_archives: Archives by Month
      yearly_archive_link: "%Y Archives"
      monthly_archive_link: "%B %Y"
    ru:
      other_news: Другие Новости
      more_news: Еще Новости...
      continue: Продолжить чтение...
      back_to_year: "Вернуться к архиву %Y года"
      recent_news: Последние Новости
      yearly_archive_title: "Архив %Y года"
      monthly_archive_title: "%B %Y архив"
      yearly_archives: Архивы по годам
      monthly_archives: Архивы по месяцам
      yearly_archive_link: "Архив %Y"
      monthly_archive_link: "%B %Y"

